name: 'Docker Sidecar'
description: 'Set up a Linux Docker sidecar for Windows and macOS runners'
author: 'Aleksandr Britvin'

inputs:
  certificates-encryption-key:
    description: 'Key to encrypt certificates before uploading'
    default: ''
    required: false

runs:
  using: 'node20'
  main: dist/index.js
